# Generated by Django 4.2.11 on 2024-04-09 12:40

from django.db import migrations, models
import django.db.models.deletion
import quiz.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_answer_question_alter_question_quiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(default=quiz.users.models.Quizzes.default_category, on_delete=django.db.models.deletion.CASCADE, to='users.category'),
        ),
    ]
