# Generated by Django 4.2.11 on 2024-04-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_quizzes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.category'),
        ),
    ]
