# Generated by Django 4.2.11 on 2024-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_quizzes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('F', 'Fundamental'), ('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert')], default='F', max_length=1, verbose_name='Difficulty'),
        ),
    ]
