# Generated by Django 4.2.11 on 2024-04-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_question_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
    ]
