# Generated by Django 4.2.11 on 2024-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_quizzes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='technique',
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=False, verbose_name='Multiple Answers'),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
