# Generated by Django 4.2.11 on 2024-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_quizzes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Fundamental'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(default='New Quiz', max_length=255, verbose_name='Quiz Title'),
        ),
    ]
